# Generated by Django 3.2 on 2022-04-24 08:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='用户名')),
                ('degree', models.SmallIntegerField(blank=True, choices=[(0, '高中'), (1, '专科'), (2, '本科'), (3, '硕士'), (4, '博士')], default=2, null=True, verbose_name='选择学历')),
                ('college', models.CharField(max_length=128, null=True, verbose_name='毕业学校')),
                ('mojor', models.CharField(max_length=128, null=True, verbose_name='专业名称')),
                ('grad_date', models.DateField(null=True, verbose_name='毕业时间')),
                ('card_id', models.CharField(max_length=32, unique=True, verbose_name='身份证号')),
                ('phone', models.CharField(max_length=32, unique=True, verbose_name='联系方式')),
                ('bank', models.CharField(max_length=64, verbose_name='开户行')),
                ('bank_id', models.CharField(max_length=32, unique=True, verbose_name='银行卡号')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='电子邮箱')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
                'ordering': ['grad_date', '-degree'],
            },
        ),
        migrations.CreateModel(
            name='Postion',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app01.user', verbose_name='关联用户')),
                ('is_probation', models.BooleanField(default=True, verbose_name='是否是在试用期')),
                ('is_formal', models.BooleanField(default=False, verbose_name='是否是转正')),
                ('is_direct', models.BooleanField(default=False, verbose_name='是否是直管')),
                ('entry_date', models.DateField(default=datetime.date.today, verbose_name='入职日期')),
                ('formal_date', models.DateField(null=True, verbose_name='转正日期')),
                ('quit_date', models.DateField(null=True, verbose_name='离职时间')),
                ('probation_end_date', models.DateField(null=True, verbose_name='试用期截止时间')),
                ('department', models.SmallIntegerField(choices=[(0, '商务组'), (1, '产品组'), (2, '办公室')], default=2, verbose_name='部门')),
                ('level', models.SmallIntegerField(choices=[(0, '新来的'), (1, '新来的1')], default=0, verbose_name='岗位等级')),
                ('is_manager', models.BooleanField(default=False, verbose_name='是否是主管')),
                ('is_labor', models.BooleanField(default=False, verbose_name='是否劳务')),
                ('company', models.CharField(max_length=128, verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
                'db_table': 'postion',
                'ordering': ['entry_date', '-level'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app01.user', verbose_name='关联用户')),
                ('probation_salary', models.IntegerField(verbose_name='试用期薪资')),
                ('formal_salary', models.IntegerField(verbose_name='转正后薪资')),
                ('performance_salary', models.IntegerField(verbose_name='绩效薪资')),
                ('management_salary', models.IntegerField(verbose_name='管理岗薪资')),
                ('commission', models.IntegerField(verbose_name='提成')),
                ('social', models.IntegerField(verbose_name='社保')),
                ('fund', models.IntegerField(verbose_name='公积金')),
                ('tax', models.IntegerField(verbose_name='个税')),
                ('modification_before_tax', models.IntegerField(verbose_name='税前工资调整')),
                ('modification_after_tax', models.IntegerField(verbose_name='税后工资调整')),
            ],
            options={
                'verbose_name': '薪资',
                'verbose_name_plural': '薪资',
                'db_table': 'salary',
                'ordering': ['-formal_salary', '-performance_salary'],
            },
        ),
        migrations.CreateModel(
            name='Work_Overtime',
            fields=[
                ('work_overtime_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='加班编号')),
                ('detail', models.TextField(verbose_name='详细说明')),
                ('overtime_start_datetime', models.DateTimeField(verbose_name='加班开始时间')),
                ('overtime_end_datetime', models.DateTimeField(verbose_name='结束时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '加班',
                'verbose_name_plural': '加班',
                'db_table': 'work_overtime',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, '周计划'), (1, '日报')], default=1, verbose_name='汇报类型')),
                ('time', models.DateTimeField(default=datetime.date.today, verbose_name='汇报时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '周计划与日报',
                'verbose_name_plural': '周计划与日报',
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leave_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='审批编号')),
                ('start_time', models.DateTimeField(verbose_name='请假开始日期')),
                ('end_time', models.DateTimeField(verbose_name='请假结束日期')),
                ('leave', models.SmallIntegerField(choices=[(0, '事假'), (2, '调休假')], default=0, verbose_name='请假类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.user', verbose_name='关联用户')),
            ],
        ),
    ]
