# Generated by Django 3.2 on 2022-04-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postion',
            name='entry_date',
            field=models.DateField(verbose_name='入职日期'),
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.DateTimeField(verbose_name='汇报时间'),
        ),
    ]
