# Generated by Django 3.2 on 2022-04-25 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postion',
            old_name='level',
            new_name='postion_level',
        ),
    ]
