"""
Django settings for salary project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8ow6b5xc3&1!wkjlc^4iy%o9fq@qa8!=xd*hu)w7o-0k+qt@@z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app01.apps.App01Config',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'salary.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'salary.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# simpleUI
SIMPLEUI_HOME_INFO = False
SIMPLEUI_HOME_QUICK = True
SIMPLEUI_HOME_ACTION = True
SIMPLEUI_ANALYSIS = False
SIMPLEUI_HOME_ICON = 'el el-icon-platform-eleme'
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'dynamic': False,
    'menus': [{
        'app': 'app01',
        'name': '薪酬应用',
        'icon': 'fa fa-credit-card',
        'models': [{
            'name': '用户',
            'icon': 'fa fa-user',
            'url': '/admin/app01/user/'
        },
            {
            'name': '职位',
            'icon': 'fa fa-id-card',
            'url': '/admin/app01/postion/'
        },
            {
            'name': '薪资',
            'icon': 'fa fa-credit-card',
            'url': '/admin/app01/salary/'
        },
            {
            'name': '请假',
            'icon': 'fa fa-thermometer-three-quarters',
            'url': '/admin/app01/leave/'
        },
            {
            'name': '周计划与日报',
            'icon': 'fa fa-flag',
            'url': '/admin/app01/report/'
        },
            {
            'name': '加班',
            'icon': 'fa fa-briefcase',
            'url': '/admin/app01/work_overtime/'
        },
            {
            'name': '部门',
            'icon': 'fa fa-building',
            'url': '/admin/app01/department/'
        },
            {
            'name': '岗位等级',
            'icon': 'fa fa-beer',
            'url': '/admin/app01/position_level/'
        },
            {
            'name': 'Token',
            'icon': 'fa fa-beer',
            'url': '/admin/app01/usertoken/'
        },
            {
            'name': '验证码',
            'icon': 'fa fa-beer',
            'url': '/admin/app01/usercode/'
        }]
    },
        {
        'app': 'auth',
        'name': '权限认证',
        'icon': 'fas fa-user-shield',
        'models': [
            {
                'name': '用户列表',
                'icon': 'fa fa-user',
                'url': 'auth/user/'
            },
            {
                'name': '用户组',
                'icon': 'fa fa-th-list',
                'url': 'auth/group/'
            }
        ]
    }, {
        'name': '上传数据',
        'icon': 'fa fa-table',
        'models': [
            {
                'name': '请假',
                'icon': 'fa fa-user',
                'url': 'http://127.0.0.1/load/leave.html'
            },
            {
                'name': '日报',
                'icon': 'fa fa-th-list',
                'url': 'http://127.0.0.1/load/report_day.html'
            },
            {
                'name': '周计划',
                'icon': 'fa fa-th-list',
                'url': 'http://127.0.0.1/load/report_week.html'
            }
        ]
    },{
        'name': '数据统计',
        'icon': 'fa fa-table',
        'models': [
            {
                'name': '请假',
                'icon': 'fa fa-user',
                'url': 'http://127.0.0.1/statistic/leave.html'
            },
            {
                'name': '日报与周计划',
                'icon': 'fa fa-th-list',
                'url': 'http://127.0.0.1/statistic/report.html'
            }
        ]
    }]
}


# 发送邮箱验证码
EMAIL_HOST = "smtp.qq.com"
EMAIL_PORT = 25
EMAIL_HOST_USER = ""
EMAIL_HOST_PASSWORD = ""
EMAIL_USE_TLS = True
EMAIL_FROM = "rechi@foxmail.com" 

STATIC_ROOT = '/static/'
STATIC_URL = '/static/'